#!/usr/bin/env bash

# Required variables
MODNAME="${MODNAME:-$MOD}"
INSTALLDIR="${DESTDIR:-$INSTALLDIR}"

[ -z "$MODNAME" ] && exit 1
[ -z "$INSTALLDIR" ] && exit 1

# $INSTALLDIR is the parent folder
INSTALLDIR="$INSTALLDIR/$MODNAME"

# balatro-mods directory
WORKDIR="$(dirname "$(realpath "${BASH_SOURCE[@]}")")" # dev environment
WORKSPACE="$(dirname "$WORKDIR")" # project workspace

MODDIR="$WORKSPACE/$MODNAME"
TARGET="${1:-dev}"

# files to skip from copy
IGNORE=('README.md'
        '.gitignore'
        'images'
        '.luarc.json')

IGNORE_FILES=("${IGNORE_FILES:-${IGNORE[@]}}")

pushdir() {
  pushd "$1" &>/dev/null || exit 1
}

popdir() {
  popd &>/dev/null || exit 1
}

do_install() {
  local from="$1"
  local to="$2"

  [ ! -d "$to" ] && mkdir -p "$to"

  pushdir "$from"
  for file in *; do
    if [[ ! "${IGNORE_FILES[*]}" =~ $file ]]; then
      cp -r "$from/$file" "$to/"
    fi
  done
  popdir
}


if [ "$TARGET" == "dev" ]; then
  echo ":: Installing for development..."
  echo ":: Installing files for $MODNAME"
  do_install "$MODDIR" "$INSTALLDIR"
else
  echo ":: Installing for release..."
  echo ":: Installing files for $MODNAME..."
  do_install "$MODDIR" "$INSTALLDIR"

  echo ":: Installng common files..."
  do_install "$WORKSPACE/common" "$INSTALLDIR/common"

  echo ":: Creating release file..."
  BASEINSTALL="$(realpath "$INSTALLDIR/..")"
  pushdir "$BASEINSTALL"
  RELFILENAME="$MODNAME-v$(cat "$MODDIR/VERSION")".zip
  SUMSFILENAME="$RELFILENAME.sha256sums"

  zip -r "$BASEINSTALL/$RELFILENAME" "$MODNAME"
  sha256sum "$RELFILENAME" > "$SUMSFILENAME"
  popdir
fi
