#!/usr/bin/env bash

DEVDIR="$(dirname "$(realpath "${BASH_SOURCE[@]}")")" # dev environment
NOLOVELY=${NOLOVELY:-false}
RUNMODE="${RUNMODE:-"normal"}"

export INSTALLDIR="$XDG_CONFIG_HOME/love/Mods"
export MODNAME="${MODNAME:-""}"

if [ ! -d "$INSTALLDIR/smods" ]; then
  cp -r "$DEVDIR/smods" "$INSTALLDIR"
fi

if [ "$RUNMODE" == "dev" ]
then
  cp -r "$DEVDIR/test" "$INSTALLDIR"
fi

if [ ! "$MODNAME" = "" ]
then
  "$DEVDIR/install"
fi

if [ "$NOLOVELY" = true ]
then
  _PRELOAD=""
else
  _PRELOAD="$DEVDIR/lovely/target/release/liblovely.so"
  if [ ! -f "$_PRELOAD" ]
  then
    pushd "$DEVDIR/lovely" &>/dev/null || exit
    cargo build --release
    popd || exit
  fi
fi

LD_PRELOAD="$_PRELOAD" love "$DEVDIR/balatro"
