#!/usr/bin/env bash

WORKDIR="$(dirname "$(realpath "${BASH_SOURCE[@]}")")" # dev environment
NOLOVELY=${NOLOVELY:-false}

export INSTALLDIR="$XDG_CONFIG_HOME/love/Mods"
export MODNAME="${MODNAME:-""}"

if [ ! -d "$INSTALLDIR/smods" ]; then
  cp -r "$WORKDIR/smods" "$INSTALLDIR"
fi

if [ ! "$MODNAME" = "" ]
then
  "$WORKDIR/install"
fi

if [ "$NOLOVELY" = true ]
then
  love "$WORKDIR/balatro"
else
  LD_PRELOAD="$WORKDIR/lovely/target/release/liblovely.so" love "$WORKDIR/balatro"
fi
